using System.IO;
using System.Linq;
using Arronix.Abstractions.Shape;

namespace Arronix.Plugin.Movies.Tests.ClientContract;

/// <summary>
/// The serialized movie the G07 browser proof reads.
/// </summary>
/// <remarks>
/// The file is generated by the contract's own writer and compared byte for byte, so a change to the movie
/// graph, the wire form or the serialization options fails here rather than surfacing as a browser that
/// renders less than it used to. Set <c>ARRONIX_REGENERATE_G07_FIXTURE=1</c> to rewrite it.
/// </remarks>
[TestFixture]
public sealed class MovieFixtureTests
{
    [Test]
    public void ThePublishedFixtureIsExactlyWhatThisContractWrites()
    {
        var expected = MovieFixture.Serialize();
        var path = MovieFixture.Path();

        if (Environment.GetEnvironmentVariable(MovieFixture.RegenerateVariable) is { Length: > 0 })
        {
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllBytes(path, expected);
            Assert.Pass($"Regenerated {MovieFixture.RelativePath} ({expected.Length} bytes).");
        }

        Assert.That(File.Exists(path), Is.True, $"{MovieFixture.RelativePath} is missing.");

        // Byte for byte: the browser is handed this file, not a re-serialization of it, so anything the
        // writer would produce differently is a payload the proof never exercised.
        Assert.That(
            File.ReadAllBytes(path),
            Is.EqualTo(expected),
            $"{MovieFixture.RelativePath} is not what this contract writes. Regenerate it with "
            + $"{MovieFixture.RegenerateVariable}=1.");
    }

    [Test]
    public void ThePublishedFixtureReadsBackAsTheCanonicalMovie()
    {
        var restored = (Movie)MovieFixture.Declaration.Deserialize(File.ReadAllBytes(MovieFixture.Path()));

        Assert.Multiple(() =>
        {
            Assert.That(restored.Title, Is.EqualTo("Inception"));
            Assert.That(restored.Year, Is.EqualTo(2010));
            Assert.That(restored.Runtime, Is.EqualTo(TimeSpan.FromMinutes(148)));
            Assert.That(restored.Ratings.Select(rating => rating.Source), Is.EqualTo(new[] { "tmdb", "critics" }));
            Assert.That(restored.Ratings[0].Scale.Maximum, Is.EqualTo(10m));
            Assert.That(restored.Collections.Single().MemberCount, Is.EqualTo(11));
            Assert.That(restored.Lifecycle.Digital, Is.EqualTo(new DateOnly(2010, 11, 23)));

            // Computed by movie-owned code from the milestones that were read, never carried on the wire.
            Assert.That(restored.Status, Is.EqualTo(MovieReleaseStage.Released));

            Assert.That(restored.Artwork.TryGet("poster", out var poster), Is.True);
            Assert.That(poster!.Address.ToString(), Is.EqualTo(MovieFixture.PosterAddress));
            Assert.That(poster.Width, Is.EqualTo(8));
            Assert.That(poster.Height, Is.EqualTo(12));
        });
    }

    [Test]
    public void ThePublishedFixtureProjectsArtworkRatingsLifecycleStatusAndCollections()
    {
        var entity = MovieFixture.Declaration.Deserialize(File.ReadAllBytes(MovieFixture.Path()));
        var projection = MovieFixture.Declaration.Project(entity);

        FieldValue Value(string fieldId) =>
            projection.Fields.Single(field => field.Descriptor.FieldId == fieldId).Value;

        Assert.Multiple(() =>
        {
            var artwork = Value("artwork");
            Assert.That(artwork.IsAbsent, Is.False);
            Assert.That(artwork.Items, Has.Count.EqualTo(2));
            Assert.That(artwork.Items![0].Image!.Role, Is.EqualTo("poster"));
            Assert.That(artwork.Items[0].Image!.Width, Is.EqualTo(8));
            Assert.That(artwork.Items[0].Image!.Height, Is.EqualTo(12));
            Assert.That(artwork.Items[1].Image!.Role, Is.EqualTo("fanart"));

            var ratings = Value("ratings");
            Assert.That(ratings.Kind, Is.EqualTo(FieldValueKind.Composite));
            Assert.That(ratings.Items, Has.Count.EqualTo(2));

            var lifecycle = Value("lifecycle");
            Assert.That(lifecycle.Kind, Is.EqualTo(FieldValueKind.Composite));
            Assert.That(lifecycle.IsAbsent, Is.False);

            var status = Value("status");
            Assert.That(status.Kind, Is.EqualTo(FieldValueKind.Enumerated));
            Assert.That(status.Text, Is.EqualTo("released"));

            var collections = Value("collections");
            Assert.That(collections.Items, Has.Count.EqualTo(1));
        });
    }

    /// <remarks>
    /// The one property the browser half depends on: nothing in the payload names a host the proof would
    /// have to reach, so the same file renders the same way on a machine with no network at all.
    /// </remarks>
    [Test]
    public void EveryImageInTheFixtureIsInline()
    {
        var restored = (Movie)MovieFixture.Declaration.Deserialize(File.ReadAllBytes(MovieFixture.Path()));

        var addresses = restored.Artwork.Images
            .Concat(restored.Collections.SelectMany(collection => collection.Artwork.Images))
            .Select(image => image.Address.Scheme)
            .Distinct()
            .ToArray();

        Assert.That(addresses, Is.EqualTo(new[] { "data" }));
    }
}
