<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Arronix.Format.Video.Tests</RootNamespace>
    <AssemblyName>Arronix.Format.Video.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TestProject>true</TestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arronix.Format.Video\Arronix.Format.Video.csproj" />
  </ItemGroup>
</Project>
