using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Arronix.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class MediaShapeGenerator : IIncrementalGenerator
{
    private const string MediaTypeName = "Arronix.Abstractions.Media.MediaType<TItem, TTarget, TRelease, TParser>";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var definitions = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (syntax, _) => FindDefinition(syntax))
            .Where(static definition => definition is not null)
            .Select(static (definition, _) => definition!);

        context.RegisterSourceOutput(definitions, static (production, definition) =>
            production.AddSource(
                definition.HintName,
                SourceText.From(Emit(definition), Encoding.UTF8)));
    }

    private static Definition? FindDefinition(GeneratorSyntaxContext context)
    {
        var declaration = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        var mediaBase = symbol.BaseType;
        while (mediaBase is not null
               && mediaBase.OriginalDefinition.ToDisplayString() != MediaTypeName)
        {
            mediaBase = mediaBase.BaseType;
        }

        if (mediaBase is null || mediaBase.TypeArguments.Length != 4)
        {
            return null;
        }

        var item = mediaBase.TypeArguments[0];
        var related = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);
        CollectReferencedEntities(item, related);
        related.Remove(item);

        foreach (var creation in declaration.DescendantNodes().OfType<BaseObjectCreationExpressionSyntax>())
        {
            if (context.SemanticModel.GetTypeInfo(creation).Type is not INamedTypeSymbol created
                || created.TypeArguments.Length != 2)
            {
                continue;
            }

            var definitionName = created.OriginalDefinition.ToDisplayString();
            if (definitionName is
                "Arronix.Abstractions.Media.GroupDefinition<TItem, TGroup>"
                or "Arronix.Abstractions.Media.WorkbenchDefinition<TItem, TRow>")
            {
                related.Add(created.TypeArguments[1]);
                CollectReferencedEntities(created.TypeArguments[1], related);
            }
        }

        var namespaceName = symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : symbol.ContainingNamespace.ToDisplayString();

        return new Definition(
            symbol,
            item,
            related.ToImmutableArray(),
            namespaceName,
            Sanitize(symbol.ToDisplayString()) + ".MediaShape.g.cs");
    }

    private static void CollectReferencedEntities(ITypeSymbol type, ISet<ITypeSymbol> found)
    {
        if (type is not INamedTypeSymbol named || !found.Add(type))
        {
            return;
        }

        foreach (var property in PublicProperties(named))
        {
            var candidate = UnwrapList(property.Type) ?? property.Type;
            if (Implements(candidate, "Arronix.Abstractions.Media.IMediaEntity"))
            {
                CollectReferencedEntities(candidate, found);
            }
        }
    }

    private static string Emit(Definition definition)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        if (definition.Namespace is not null)
        {
            source.Append("namespace ").Append(definition.Namespace).AppendLine(";");
            source.AppendLine();
        }

        var accessibility = definition.Symbol.DeclaredAccessibility == Accessibility.Public
            ? "public"
            : "internal";
        source.Append(accessibility).Append(' ');
        if (definition.Symbol.IsSealed)
        {
            source.Append("sealed ");
        }

        source.Append("partial class ").Append(definition.Symbol.Name).AppendLine();
        source.AppendLine("{");
        source.AppendLine("    /// <inheritdoc />");
        source.AppendLine("    public override global::Arronix.Abstractions.Media.CompiledShapeCatalog CompiledShapes { get; } =");
        source.AppendLine("        new(");
        source.AppendLine("            ItemShape,");
        source.AppendLine("            new global::Arronix.Abstractions.Media.CompiledEntityShape[]");
        source.AppendLine("            {");

        for (var index = 0; index < definition.Related.Length; index++)
        {
            source.Append("                RelatedShape").Append(index).AppendLine(",");
        }

        source.AppendLine("            });");
        source.AppendLine();
        EmitShape(source, "ItemShape", definition.Item);

        for (var index = 0; index < definition.Related.Length; index++)
        {
            source.AppendLine();
            EmitShape(source, "RelatedShape" + index, definition.Related[index]);
        }

        source.AppendLine("}");
        return source.ToString();
    }

    private static void EmitShape(StringBuilder source, string name, ITypeSymbol type)
    {
        source.Append("    private static global::Arronix.Abstractions.Media.CompiledEntityShape ")
            .Append(name).AppendLine(" { get; } = new()");
        source.AppendLine("    {");
        source.Append("        EntityType = typeof(").Append(TypeName(type)).AppendLine("),");
        source.AppendLine("        Fields = new global::Arronix.Abstractions.Media.CompiledField[]");
        source.AppendLine("        {");

        foreach (var property in PublicProperties((INamedTypeSymbol)type))
        {
            if (!Has(property, "IgnoreAttribute") && property.Name != "EqualityContract")
            {
                EmitField(source, property, "            ", topLevel: true, new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default));
            }
        }

        source.AppendLine("        },");
        source.AppendLine("    };");
    }

    private static void EmitField(
        StringBuilder source,
        IPropertySymbol property,
        string indent,
        bool topLevel,
        ISet<ITypeSymbol> ancestors)
    {
        var declared = property.Type;
        var listElement = UnwrapList(declared);
        var multivalued = listElement is not null || Is(declared, "Arronix.Abstractions.Media.ArtworkSet")
            || Is(declared, "Arronix.Abstractions.Media.ExternalIdSet");
        var element = StripNullable(listElement ?? declared);
        var kind = ValueKind(element, property);
        var nullable = IsNullable(declared) || (listElement is not null && IsNullable(listElement));
        var semantics = topLevel ? Semantics(property, kind, element) : 0;
        var prominence = topLevel ? Prominence(property) : 1;
        var editable = topLevel && Has(property, "EditableAttribute") && !Has(property, "DerivedAttribute");
        var display = Attribute(property, "DisplayAttribute");
        var name = NamedString(display, "Name") ?? Label(property.Name);
        var description = NamedString(display, "Description");
        var example = NamedString(display, "Example");
        var unit = ConstructorString(Attribute(property, "UnitAttribute"));
        var operators = Operators(kind, multivalued, nullable);
        var isNameable = kind is not (18 or 12 or 20);

        source.Append(indent).AppendLine("new global::Arronix.Abstractions.Media.CompiledField");
        source.Append(indent).AppendLine("{");
        source.Append(indent).Append("    PropertyName = ").Append(Literal(property.Name)).AppendLine(",");
        source.Append(indent).Append("    PropertyType = typeof(").Append(TypeName(declared)).AppendLine("),");
        source.Append(indent).Append("    ElementType = typeof(").Append(TypeName(element)).AppendLine("),");
        source.Append(indent).Append("    IsNullable = ").Append(Bool(nullable)).AppendLine(",");
        source.Append(indent).Append("    Example = ").Append(LiteralOrNull(example)).AppendLine(",");
        source.Append(indent).Append("    IsNameable = ").Append(Bool(isNameable)).AppendLine(",");
        source.Append(indent).Append("    ExplicitIdentity = ").Append(Bool(Has(property, "IdentityAttribute"))).AppendLine(",");
        source.Append(indent).Append("    FilterOperators = (global::Arronix.Abstractions.Intent.FilterOperators)")
            .Append(operators).AppendLine(",");
        source.Append(indent).Append("    Read = static instance => ((")
            .Append(TypeName(property.ContainingType)).Append(")instance).")
            .Append(property.Name).AppendLine(",");
        source.Append(indent).AppendLine("    Descriptor = new global::Arronix.Abstractions.Shape.FieldDescriptor");
        source.Append(indent).AppendLine("    {");
        source.Append(indent).Append("        FieldId = ").Append(Literal(Identifier(property.Name))).AppendLine(",");
        source.Append(indent).Append("        Name = ").Append(Literal(name)).AppendLine(",");
        source.Append(indent).Append("        Description = ").Append(LiteralOrNull(description)).AppendLine(",");
        source.Append(indent).Append("        ValueKind = (global::Arronix.Abstractions.Shape.FieldValueKind)")
            .Append(kind).AppendLine(",");
        source.Append(indent).Append("        Semantics = (global::Arronix.Abstractions.Shape.FieldSemantics)")
            .Append(semantics).AppendLine(",");
        source.Append(indent).Append("        Prominence = (global::Arronix.Abstractions.Shape.Prominence)")
            .Append(prominence).AppendLine(",");
        source.Append(indent).Append("        Multivalued = ").Append(Bool(multivalued)).AppendLine(",");
        source.Append(indent).Append("        Editable = ").Append(Bool(editable)).AppendLine(",");
        source.Append(indent).Append("        Unit = ").Append(LiteralOrNull(unit)).AppendLine(",");
        EmitChoices(source, element, kind, indent + "        ");
        EmitComponentDescriptors(source, element, kind, indent + "        ", ancestors);
        source.Append(indent).AppendLine("    },");
        EmitComponents(source, element, kind, indent + "    ", ancestors);
        source.Append(indent).AppendLine("},");
    }

    private static void EmitChoices(StringBuilder source, ITypeSymbol element, int kind, string indent)
    {
        if (kind != 11 || element is not INamedTypeSymbol enumeration)
        {
            source.Append(indent).AppendLine("Choices = global::System.Array.Empty<global::Arronix.Abstractions.Shape.FacetValue>(),");
            return;
        }

        source.Append(indent).AppendLine("Choices = new global::Arronix.Abstractions.Shape.FacetValue[]");
        source.Append(indent).AppendLine("{");
        foreach (var member in enumeration.GetMembers().OfType<IFieldSymbol>().Where(static field => field.HasConstantValue))
        {
            source.Append(indent).Append("    new(").Append(Literal(Identifier(member.Name))).Append(", ")
                .Append(Literal(Label(member.Name))).AppendLine("),");
        }
        source.Append(indent).AppendLine("},");
    }

    private static void EmitComponentDescriptors(
        StringBuilder source,
        ITypeSymbol element,
        int kind,
        string indent,
        ISet<ITypeSymbol> ancestors)
    {
        if (kind != 20 || element is not INamedTypeSymbol composite || ancestors.Contains(element))
        {
            source.Append(indent).AppendLine("Components = global::System.Array.Empty<global::Arronix.Abstractions.Shape.FieldDescriptor>(),");
            return;
        }

        var next = new HashSet<ITypeSymbol>(ancestors, SymbolEqualityComparer.Default) { element };
        source.Append(indent).AppendLine("Components = new global::Arronix.Abstractions.Shape.FieldDescriptor[]");
        source.Append(indent).AppendLine("{");
        foreach (var component in PublicProperties(composite))
        {
            if (!Has(component, "IgnoreAttribute") && component.Name != "EqualityContract")
            {
                EmitDescriptorOnly(source, component, indent + "    ", next);
            }
        }
        source.Append(indent).AppendLine("},");
    }

    private static void EmitDescriptorOnly(
        StringBuilder source,
        IPropertySymbol property,
        string indent,
        ISet<ITypeSymbol> ancestors)
    {
        var listElement = UnwrapList(property.Type);
        var multivalued = listElement is not null;
        var element = StripNullable(listElement ?? property.Type);
        var kind = ValueKind(element, property);
        var display = Attribute(property, "DisplayAttribute");

        source.Append(indent).AppendLine("new global::Arronix.Abstractions.Shape.FieldDescriptor");
        source.Append(indent).AppendLine("{");
        source.Append(indent).Append("    FieldId = ").Append(Literal(Identifier(property.Name))).AppendLine(",");
        source.Append(indent).Append("    Name = ").Append(Literal(NamedString(display, "Name") ?? Label(property.Name))).AppendLine(",");
        source.Append(indent).Append("    ValueKind = (global::Arronix.Abstractions.Shape.FieldValueKind)").Append(kind).AppendLine(",");
        source.Append(indent).Append("    Multivalued = ").Append(Bool(multivalued)).AppendLine(",");
        EmitChoices(source, element, kind, indent + "    ");
        EmitComponentDescriptors(source, element, kind, indent + "    ", ancestors);
        source.Append(indent).AppendLine("},");
    }

    private static void EmitComponents(
        StringBuilder source,
        ITypeSymbol element,
        int kind,
        string indent,
        ISet<ITypeSymbol> ancestors)
    {
        if (kind != 20 || element is not INamedTypeSymbol composite || ancestors.Contains(element))
        {
            source.Append(indent).AppendLine("Components = global::System.Array.Empty<global::Arronix.Abstractions.Media.CompiledField>(),");
            return;
        }

        var next = new HashSet<ITypeSymbol>(ancestors, SymbolEqualityComparer.Default) { element };
        source.Append(indent).AppendLine("Components = new global::Arronix.Abstractions.Media.CompiledField[]");
        source.Append(indent).AppendLine("{");
        foreach (var component in PublicProperties(composite))
        {
            if (!Has(component, "IgnoreAttribute") && component.Name != "EqualityContract")
            {
                EmitField(source, component, indent + "    ", topLevel: false, next);
            }
        }
        source.Append(indent).AppendLine("},");
    }

    private static IReadOnlyList<IPropertySymbol> PublicProperties(INamedTypeSymbol type)
    {
        var hierarchy = new Stack<INamedTypeSymbol>();
        for (var current = type; current is not null; current = current.BaseType)
        {
            hierarchy.Push(current);
        }

        var result = new List<IPropertySymbol>();
        var positions = new Dictionary<string, int>(StringComparer.Ordinal);
        while (hierarchy.Count > 0)
        {
            foreach (var property in hierarchy.Pop().GetMembers().OfType<IPropertySymbol>())
            {
                if (property.IsStatic || property.Parameters.Length != 0
                    || property.DeclaredAccessibility != Accessibility.Public
                    || property.GetMethod?.DeclaredAccessibility != Accessibility.Public)
                {
                    continue;
                }

                if (positions.TryGetValue(property.Name, out var position))
                {
                    result[position] = property;
                }
                else
                {
                    positions[property.Name] = result.Count;
                    result.Add(property);
                }
            }
        }
        return result;
    }

    private static int ValueKind(ITypeSymbol type, IPropertySymbol property)
    {
        if (Has(property, "SizeAttribute")) return 8;
        if (Has(property, "CountAttribute")) return 19;
        if (Has(property, "RatioAttribute")) return 9;
        if (type.SpecialType == SpecialType.System_String) return Has(property, "MultilineAttribute") ? 1 : 0;
        if (type.TypeKind == TypeKind.Enum) return 11;
        if (Is(type, "Arronix.Abstractions.Media.ArtworkSet") || Is(type, "Arronix.Abstractions.Media.ArtworkImage")) return 18;
        if (Is(type, "Arronix.Abstractions.Media.ExternalIdSet") || Is(type, "Arronix.Abstractions.Shape.ExternalId")) return 13;
        if (Is(type, "Arronix.Abstractions.Identity.MediaItemId")) return 2;
        if (type.SpecialType is SpecialType.System_Int16 or SpecialType.System_Int32 or SpecialType.System_Int64) return 2;
        if (type.SpecialType is SpecialType.System_Single or SpecialType.System_Double or SpecialType.System_Decimal) return 3;
        if (type.SpecialType == SpecialType.System_Boolean) return 4;
        if (Is(type, "System.DateOnly")) return 5;
        if (Is(type, "System.DateTime") || Is(type, "System.DateTimeOffset")) return 6;
        if (Is(type, "System.TimeSpan")) return 7;
        if (Is(type, "System.Uri")) return 14;
        if (Is(type, "Arronix.Abstractions.FileSystem.PlatformPath")) return 15;
        if (Is(type, "Arronix.Abstractions.DTOs.Language")) return 16;
        if (Is(type, "Arronix.Abstractions.DTOs.QualityTier")) return 17;
        if (Is(type, "Arronix.Abstractions.Shape.OrdinalPath")) return 10;
        if (Implements(type, "Arronix.Abstractions.Media.IMediaEntity")) return 12;
        return 20;
    }

    private static int Semantics(IPropertySymbol property, int kind, ITypeSymbol element)
    {
        var result = 0;
        if (Has(property, "IdentityAttribute")) result |= 1;
        if (Has(property, "TitleAttribute")) result |= 2;
        if (Has(property, "SortableAttribute")) result |= 8;
        if (Has(property, "FilterableAttribute")) result |= 16;
        if (Has(property, "GroupableAttribute")) result |= 32;
        if (Has(property, "SearchableAttribute")) result |= 64;
        if (Has(property, "ProgressAttribute")) result |= 128;
        if (Has(property, "StatusAttribute")) result |= 256;
        if (Has(property, "TimestampAttribute")) result |= 512;
        if (Has(property, "SizeAttribute")) result |= 1024;
        if (Has(property, "ArtworkAttribute")) result |= 2048;
        if (Has(property, "DisambiguationAttribute")) result |= 4096;

        if (Implements(property.ContainingType, "Arronix.Abstractions.Media.IMediaEntity"))
        {
            if (property.Name == "Key") result |= 1;
            if (property.Name == "Title") result |= 2 | 8;
            if (property.Name == "Artwork") result |= 2048;
        }

        if (Implements(property.ContainingType, "Arronix.Abstractions.Media.IMediaItem"))
        {
            if (property.Name == "Status") result |= 256 | 8 | 16 | 32;
            if (property.Name == "CatalogState" || property.Name == "Collections") result |= 16 | 32;
        }

        if (kind == 13) result |= 1;
        if (kind == 18 || Is(element, "Arronix.Abstractions.Media.ArtworkSet")) result |= 2048;
        return result;
    }

    private static int Prominence(IPropertySymbol property)
    {
        var attribute = Attribute(property, "ProminenceAttribute");
        if (attribute?.ConstructorArguments.Length > 0 && attribute.ConstructorArguments[0].Value is int value)
        {
            return value;
        }

        if (property.Name == "Status" || property.Name == "Collections") return 1;
        if (property.Name == "CatalogState") return 3;
        return 2;
    }

    private static int Operators(int kind, bool multivalued, bool nullable)
    {
        int value;
        if (multivalued) value = 64 | 4;
        else if (kind is 0 or 1 or 15) value = 4 | 1;
        else if (kind is 2 or 3 or 8 or 9 or 19) value = 1 | 64 | 8 | 16 | 32;
        else if (kind is 5 or 6 or 7) value = 8 | 16 | 32;
        else if (kind is 11 or 17 or 16) value = 1 | 2 | 64;
        else value = 1;
        return nullable ? value | 128 : value;
    }

    private static ITypeSymbol? UnwrapList(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol named || !named.IsGenericType) return null;
        var definition = named.OriginalDefinition.ToDisplayString();
        return definition is "System.Collections.Generic.IReadOnlyList<T>"
            or "System.Collections.Generic.IReadOnlyCollection<T>"
            or "System.Collections.Generic.IEnumerable<T>"
            ? named.TypeArguments[0]
            : null;
    }

    private static ITypeSymbol StripNullable(ITypeSymbol type) =>
        type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullable
            ? nullable.TypeArguments[0]
            : type;

    private static bool IsNullable(ITypeSymbol type) =>
        type.IsReferenceType || type.NullableAnnotation == NullableAnnotation.Annotated
        || type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T };

    private static bool Implements(ITypeSymbol type, string interfaceName) =>
        Is(type, interfaceName) || type.AllInterfaces.Any(candidate => Is(candidate, interfaceName));

    private static bool Is(ITypeSymbol type, string fullName) =>
        type.WithNullableAnnotation(NullableAnnotation.None)
            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::" + fullName;

    private static AttributeData? Attribute(IPropertySymbol property, string shortName) =>
        property.GetAttributes().FirstOrDefault(attribute => attribute.AttributeClass?.Name == shortName);

    private static bool Has(IPropertySymbol property, string shortName) => Attribute(property, shortName) is not null;

    private static string? NamedString(AttributeData? attribute, string name) =>
        attribute?.NamedArguments.FirstOrDefault(pair => pair.Key == name).Value.Value as string;

    private static string? ConstructorString(AttributeData? attribute) =>
        attribute?.ConstructorArguments.Length > 0 ? attribute.ConstructorArguments[0].Value as string : null;

    private static string TypeName(ITypeSymbol type) =>
        type.WithNullableAnnotation(NullableAnnotation.None)
            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string Identifier(string name) =>
        name.Length == 0 ? name : char.ToLowerInvariant(name[0]) + name.Substring(1);

    private static string Label(string name)
    {
        var result = new StringBuilder();
        for (var index = 0; index < name.Length; index++)
        {
            var startsWord = index > 0 && char.IsUpper(name[index]) && !char.IsUpper(name[index - 1]);
            if (startsWord) result.Append(' ');
            result.Append(startsWord ? char.ToLowerInvariant(name[index]) : name[index]);
        }
        return result.ToString();
    }

    private static string Literal(string value) => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static string LiteralOrNull(string? value) => value is null ? "null" : Literal(value);

    private static string Bool(bool value) => value ? "true" : "false";

    private static string Sanitize(string value)
    {
        var result = new StringBuilder(value.Length);
        foreach (var character in value)
        {
            result.Append(char.IsLetterOrDigit(character) ? character : '_');
        }
        return result.ToString();
    }

    private sealed class Definition
    {
        internal Definition(
            INamedTypeSymbol symbol,
            ITypeSymbol item,
            ImmutableArray<ITypeSymbol> related,
            string? namespaceName,
            string hintName)
        {
            Symbol = symbol;
            Item = item;
            Related = related;
            Namespace = namespaceName;
            HintName = hintName;
        }

        internal INamedTypeSymbol Symbol { get; }

        internal ITypeSymbol Item { get; }

        internal ImmutableArray<ITypeSymbol> Related { get; }

        internal string? Namespace { get; }

        internal string HintName { get; }
    }
}
